INSERT INTO USER(ID, USERNAME, NOMBRE, APELLIDO, AGE) VALUES (123, 'clark', 'Clark', 'Kent', 33); 
INSERT INTO USER(ID, USERNAME, NOMBRE, APELLIDO, AGE) VALUES (124, 'kevin', 'Kevin', 'Mac Calister', 8); 

INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(123, 'Man of Steel', 'G'); 
INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(124, 'Conjuro', 'PG_13'); 
