INSERT INTO USER(ID, USERNAME, NOMBRE, APELLIDO, AGE) VALUES (123, 'clarktest', 'Clark', 'Kent', 33); 
INSERT INTO USER(ID, USERNAME, NOMBRE, APELLIDO, AGE) VALUES (124, 'kevintest', 'Kevin', 'Mac Calister', 8); 

INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(123, 'Man of Steel Test', 'G'); 
INSERT INTO MOVIE(ID, TITLE, RATING) VALUES(124, 'Conjuro Test', 'PG_13'); 
